### ISSUE TITLE
Incorrect languages output.

### ISSUE THREAD

**Issue by fabiocaccamo** [rosettatype/hyperglot#100]
Hello, 
thank you for this great library. 

I tested this library against many fonts and I noticed that the languages output has some errors:

- **English language is not included** in the supported languages list, this is very strange.
- **Italian dialects** (such as `Sicilian`, `Venetian`, ...) are not languages, they **should not be included** in the output.

---

This is the summary of my implementation:
 
```python
chars = parse_font_chars(font_path)
langs = Languages()
supported = langs.supported(chars=chars, validity=VALIDITYLEVELS[-1])
```

**Comment by moyogo** [comment]
@fabiocaccamo The distinction between dialects and languages is often political or sociological. It’s generally accepted among linguistis that Sicilian, Venetian and others are languages and not dialects of Italian when interintelligebility, vocabulary, grammar and phonology are taken into account. For example, Ethnologue.org considers Sicilian "distinct enough from Standard Italian to be considered a separate language" and a ISO 639-3 language code has been assigned to it. Several works in Sicilian typically also use an orthography distinct from Italian, with additional letters like ḍ which has no use in Italian.

For English, its validity is `preliminary`.

**Comment by fabiocaccamo** [comment]
Thank you very much for the explanation and the suggestion on the validity.
