### ISSUE TITLE
hyperglot.rosettatype.com site is not accessible (HTTP error 530)

### ISSUE THREAD

**Issue by chrissimpkins** [rosettatype/hyperglot#101]
Environment: macOS 12.6 + Chrome Version 106.0.5249.119 (Official Build) (arm64)

![9vXRZHvVGJmgSaC](https://user-images.githubusercontent.com/4249591/197843016-acb38ad7-34c2-4be7-8a4c-c6f8805d042f.png)

**Comment by MrBrezina** [comment]
Thank you for the report. It seems to work for me in Safari and Firefox. I doubt that is Chrome-related, but @kontur can investigate further, soon.

**Comment by chrissimpkins** [comment]
Seems to be back up again in the same environment.  🤷 

Must have been something temporary.  I'll close as no longer required on this end.  Thanks!
