### ISSUE TITLE
Expose what codepoints a font is missing for support of a given language

### ISSUE THREAD

**Issue by kontur** [rosettatype/hyperglot#111]

**Comment by kontur** [comment]
@skurzinz Thanks! Would you be interested in using this in the terminal, or if you'd expect this from the webapp, how would you be using this?

Note in the support view you can drop your existing font, then select any possibly unsupported languages on the left, and use the "Copy data" at the top right; would you want to explicitly get a list of _missing_ glyphs based on font + language selection?

**Comment by skurzinz** [comment]
It's perhaps more of a hypothetical use case. 

The codepoints available in an uploaded font on the web app are already there, and also the ones necessary to fully support a language/orthography (`div class="char aux not-supported"` ). 

![image](https://github.com/rosettatype/hyperglot/assets/37441365/bf4cbf93-23c4-401d-8895-3c7db1e6727c)

I couldn't get my Firefox to accept a CSS rule along the lines of 

```
li:has(div .char.aux:not(.not-supported)) {
  display: none;
}
```

for the screenshot frontend mockup, and also did not bother to style a possible place for a "show unsupported chars only" toggle that shows/hides the supported codepoints, but that IMHO would be an acceptable way of providing this info without overloading the web app.

**Comment by kontur** [comment]
Ah, now I see what you mean, you want to _see them filtered_. 

We could add two options, like with the `[ ] Show verified/unverified data` where we have a default state checked on both and you could uncheck `[+] Show supported font characters` and leave `[+] Show unsupported font characters` checked. And obviously disable those two options when in the Database mode.

@MrBrezina what do you think?

**Comment by kontur** [comment]
@skurzinz We have an option like that available now in the webapp at the top of the right panel — selections there will affect the listed and copied characters. Thanks for the feedback 👍 

<img width="853" alt="Screenshot 2023-12-13 at 13 37 47" src="https://github.com/rosettatype/hyperglot/assets/1893577/fe210851-6a82-4e49-8f71-7d1997c68e09">

**Comment by skurzinz** [comment]
Wow, nice! Thanks for so quickly dealing with this humble feature request!
