### ISSUE TITLE
Afrikaans diacritics

### ISSUE THREAD

**Issue by iandoug** [rosettatype/hyperglot#117]
Hi

Afrikaans needs á and ý

https://en.wikipedia.org/wiki/Afrikaans#Orthography

Thanks, Ian

**Comment by iandoug** [comment]
BTW they also use ç in names like François. Which is pretty common. Legacy of the French Huguenots.

**Comment by kontur** [comment]
Thanks for the pointer, I'll review and correct this with the next release.

**Comment by kontur** [comment]
Fixed in 0.5.1
