### ISSUE TITLE
İ missing in Crimean Tatar (Latin script)

### ISSUE THREAD

**Issue by arialcrime** [rosettatype/hyperglot#124]
Idotaccent `uni0130` doesn’t show up for Crimean Tatar (Latin). Both [Wikipedia](https://en.wikipedia.org/wiki/Crimean_Tatar_alphabet#Latin) and [Omniglot](https://omniglot.com/writing/crimeantatar.php) (the two sources given by hyperglot) list `İ` as being part of the Latin Crimean Tatar alphabet.

<img width="860" alt="PNG image" src="https://github.com/rosettatype/hyperglot/assets/2954154/9e0925da-4432-4385-9fbd-fc4b91f8f831">

Is it possible that this character got lost somewhere on the way to the [yaml file](https://github.com/rosettatype/hyperglot/blob/0ff93b868ab6fd85f3a47cfcd7ab73c83d3cb086/lib/hyperglot/hyperglot.yaml#L3018)? I’m not very experienced with Crimean Tatar, so I’m happy for your thoughts and /or help.

**Comment by MrBrezina** [comment]
Well spotted, thank you!
