### ISSUE TITLE
con.yaml file causes windows installation error

### ISSUE THREAD

**Issue by m4rc1e** [rosettatype/hyperglot#127]
According to @simoncozens, the file https://github.com/rosettatype/hyperglot/blob/master/lib/hyperglot/data/con.yaml is causing a windows installation error. Our google/fonts ci is failing due to this, https://github.com/google/fonts/actions/runs/5332171055/jobs/9662699019.

As a temp fix, I'm using 0.4.5.

**Comment by m4rc1e** [comment]
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by simoncozens** [comment]
https://www.youtube.com/watch?v=bC6tngl0PTI

**Comment by kontur** [comment]
There is a first for everything 🤦 Thanks for raising this.

**Comment by kontur** [comment]
@m4rc1e took a while for a new release but `0.5.2` should have this fixed.
