### ISSUE TITLE
Command line options not working as expected

### ISSUE THREAD

**Issue by justinpenner** [rosettatype/hyperglot#13]
I'm getting some confusing results when testing the command line tool.

`hyperglot font.otf` tells me 322 languages are supported.
`hyperglot -d font.otf` tells me 320 languages supported.

The `-d` option is a more lenient filter that returns supported languages if the required bases and marks exist but precomposed characters are missing, right? So shouldn't the `-d` option return more languages, not less?

I compared the lists and found that the `-d` option gave me the same list minus Hakka Chinese and Mandarin Chinese, interestingly. This raises another issue, as I'm testing a Latin font, so Chinese languages shouldn't appear in the results. Only languages that are supported in their primary script are supposed to be returned, unless I override this with the `--include-all-orthographies` option.

I also noticed that some of the 322 languages reported by the first command (i.e. Hakka Chinese and Yoruba) are not supported by the font I'm testing. The font has all the required components but it's missing some precomposed characters, such as letters with *dot below* accents (ẸỌṢẹọṣ) that are required for Yoruba, and characters with multiple accents (ǗǕǘǖ) required in Hakka Chinese, so these languages should not have been reported.

**Comment by kontur** [comment]
Thanks for the feedback, I'll review what you reported and get back to you.

The Hakka Chinese being reported for a "Latin only" (simplifying here) is an error in the data. We consider some languages to have multiple "primary" orthographies, where both are of equal status and these will match for _either_ being supported. However, Hakka Chinese should have an additional parameter that sets those to be _both_ required and only match when indeed both are supported. (The reason for this with Chinese languages being, _afaik_, that the transliteration is deemed so important as to be part of the support a font needs to have)

**Comment by kontur** [comment]
I've reviewed the `--decompose` option and there was indeed an issue that resulted in unexpected and wrong outcomes. We'll release a fix for that soon.

Let's have this issue open for now, since it also touches upon some language data that may need clarification.

**Comment by kontur** [comment]
Thanks again for the bug report. The `--decompose` flag should now behave like one would expect.
We also reviewed some languages where e.g. transliteration orthographies would match when they should not have. That said, using `--include-all-orthographies` (and possibly `--decompose`) in conjunction will still match such transliterations if the font supports them.

Please update the package with `pip install --upgrade hyperglot` and if the issue persists or you notice something else off feel free to comment here or open a new issue 👍
