### ISSUE TITLE
Please add DIN 91379 (Unicode subset for Europe)

### ISSUE THREAD

**Issue by vk-github18** [rosettatype/hyperglot#132]
Please add the letters and sequences of [DIN 91379](https://en.wikipedia.org/wiki/DIN_91379) *"Characters and defined character sequences in Unicode for the electronic processing of names and data exchange in Europe, with CD-ROM"*. 

The normative part of the standard tries to include all letters and sequences that are required for the transliteration of names to Latin script. The compliance to this standard will be mandatory for German authorities and organisations from Nov 1, 2024.

## References:
- https://en.wikipedia.org/wiki/DIN_91379
- https://github.com/String-Latin/DIN-91379-Characters-and-Sequences
- https://raw.githubusercontent.com/String-Latin/DIN-91379-Characters-and-Sequences/main/latin_list_1.3.txt List of all letters and sequences of DIN 91379

**Comment by kontur** [comment]
Generally speaking, entries in Hyperglot resemble actual languages and as such do not represent generic charsets such as this. While interesting in general and by way of "checking against some arbitrary charset", _not checking_ charsets or standards like this but _instead_ checking for _actual support of languages_ is the stated goal of Hyperglot. I'm inclined to close this as not applicable, but we can have the issue open for discussion.
