### ISSUE TITLE
‘Copy selection to clipbboard’ bug

### ISSUE THREAD

**Issue by MarcusSterz** [rosettatype/hyperglot#136]
The selection list (when pasted to a text program like TextEdit) happens to contain multiple identical language names: 

Cyrillic:
Abaza, Abaza, Abaza, Abaza, Abaza, Abaza, Abaza, Abaza, Abaza, Abaza, Adyghe, Adyghe, Adyghe, Adyghe, Adyghe, Adyghe, Adyghe, Adyghe, Adyghe, Adyghe, Aghul, Aghul, Aghul, Aghul, Aghul, Aghul, Aghul, Aghul, Aghul, Aghul, Andi, Andi, Andi, Andi, Andi, Andi, Andi, Andi, Andi, Andi, Archi, Archi, Archi, Archi, Archi, Archi, Archi, Archi, Archi, Archi, Avaric, Avaric, Avaric, Avaric, 

Love this website, though!

**Comment by kontur** [comment]
Thank you for the bug report! We have a newer version of the web app ready to launch shortly, and it will most certainly include a fix for this.
