### ISSUE TITLE
Compare to CLDR

### ISSUE THREAD

**Issue by davelab6** [rosettatype/hyperglot#14]
How does the database here compare to CLDR?

**Comment by MrBrezina** [comment]
I should have addressed this somewhere.

I think the motivations are slightly different between the CLDR’s exemplars and Hyperglot’s orthographies. CLDR’s quality is uneven. So I would say, where we differ, we tend to improve. Longer answer would require too much criticism (that I do not want to do) or actual comparison. Also, I think our `auxiliary` is conceived a little different. In CLDR, it seems that these are based on actual use of the language (data scrapping from Wikipedia comes to mind) while we use it mostly to include nice to haves or legacy code points.

**Comment by davelab6** [comment]
> the motivations are slightly different between the CLDR’s exemplars and Hyperglot’s orthographies

That's fine, but is the **resulting data** really different? 

> CLDR’s quality is uneven. So I would say, where we differ, we tend to improve.

I'm interested to understand if this started from zero or started as a fork of CLDR, and in either case, if this can be upstreamed to CLDR.

**Comment by MrBrezina** [comment]
Well I was torn between not wanting to disparage other people’s work and simply being lazy to address that. :) But your question is (and has been) legitimate and I will compile a longer response.

Yes, the our data is different from theirs. We worked from Unicode CLDR, Unicode documentation, Wikipedia, Ethnologue, as a basis and other resources we could get our hands on (@sergiolmartins mainly, my original lists are so old, I do not remember where they come from). Ideally, I would like those where we found better data to feed back into CLDR. Yes to a lot of junk, but I absolutely understand, we also did a beta first. I really hope the web interface and ability to use it via CLI and package are beneficial here.

**Comment by sergiolmartins** [comment]
I'll add a bit more to the above reply.
The lists were reached by cross-referencing several sources, as mentioned and any other documents I managed to find, be it dictionaries or some other learning documentation that seemed trustworthy – the best seemed to be linguistic articles and studies, if I was lucky enough to find them. I would also need to be able to parse these, so there must be quite a bit of info still out there in languages I don't speak.
Another trouble with a lot of these sources is that they end up referencing each other – in more than one case Omniglot and Wikipedia point to each other as (partial) sources of information. Most of this was hand-sifted, but that doesn't mean it has no errors, in fact it would be a major point to get native speakers to veto or verify what we've put together.

**Comment by alerque** [comment]
>  I really hope the web interface and ability to use it via CLI and package are beneficial here.

Sure they are! But that isn't the question. The question is about the data. In fact this highlights something I'm convinced is a major mistake in this project: the data set should be one project and the CLI tooling should be another. Having these coupled in one repository will be a serious limitation down the road. The data may well prove useful in other contexts where the tooling would be clutter, and the tooling should be decoupled from the data versioning so people can potentially use the tooling with different data (older versions, a fork for contested data, substituting CLDR data, etc.). Perhaps some day you want to rework the tooling a bit so the CLI works differently. That may break a lot of old projects that would otherwise refresh their data, but now the tooling would block them.

**Comment by kontur** [comment]
Note to self: Do programmatic diff to CLDR data, [e.g.](https://github.com/unicode-org/cldr/tree/release-38-1/common/main)

**Comment by MrBrezina** [comment]
@davelab6 added the first draft of the comparison [here](README_comparison.md). Let me know if something is missing, not clear. There might be something I missed about CLDR.

@kontur added this to the roadmap in README and in a new issue #52
