### ISSUE TITLE
In webapp, the use of the `locl` feature for Romanian causes confusion

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#153]
The preview of the “s/t with cedilla” look like “s/t with comma accent below” which is confusing. Is this an issue in the font (the substitution should not happen). Is there a way, we could make this clear in the web app?

<img width="759" alt="Screenshot 2024-01-15 at 16 22 01" src="https://github.com/rosettatype/hyperglot/assets/485475/ec52f436-6c98-400b-9b9e-d9a5ec055c70">

**Comment by danburzo** [comment]
To disable the `locl` feature for the Romanian language charset tables, I can suggest this CSS rule:

```css
.charset:lang(ro) {
  font-feature-settings: 'locl' 0;
}
```

**Comment by kontur** [comment]
Thanks for pointing that out. That CSS will indeed show the cedilla versions of the auxiliary characters, but I need to have a think about how this should be triggered. Generally speaking, we do want the `locl` triggered for charsets, but in this case the font does transformations also on the encoded auxiliary characters to make them look the same as the base ones.

I think we _could_ hard code this in the site CSS for Romanian and auxiliary charset, specifically, if this is really the only such occurrence throughout the entire database.

**Comment by kontur** [comment]
Yes, it's a bit of both. From the note below the orthography:

> … To resolve this and to avoid discrepancy (the marks below both character pairs ought to be identical) some font developers use automated substitutions in their OpenType fonts.

In this sense the font is doing the right thing rendering them identical. For communicating the issue of legacy codepoints, however, it might make it more understandable if the cedilla ones looked like having cedillas, even if we have to overwrite the font behavior to achieve this. We can additionally use `design_alternates` for those cedilla shaped ones, which will add a highlight to those specific characters in the app to associate the note with them, which would make the relation more clear, too.

**Comment by kontur** [comment]
<img width="901" alt="Screenshot 2024-01-30 at 9 50 41" src="https://github.com/rosettatype/hyperglot/assets/1893577/06366523-f03a-43e0-a9f5-138d41891ce4">

This is now implemented in `0.6.1` and on the webapp. The `design_alternates` explicitly highlight the characters, and the aux cedilla variants use cedilla forms of Noto _for clarity_ (although Noto normally does _correctly_ shape them as comma forms for Romanian locale).

**Comment by danburzo** [comment]
Awesome, thank you for addressing the issue!
