### ISSUE TITLE
Review Latin: Serbian definitions

### ISSUE THREAD

**Issue by MariannaPaszkowska** [rosettatype/hyperglot#158]
Hi, could you please review the support for Latin:Serbian/Srpski?

It seems to me that even though I added all Serbian characters recommended by the "DATABASE VIEW" of https://hyperglot.rosettatype.com/ the hyperglot still doesn't recognise that the font contains it.

I also did some testing with the terminal tool. Here is the snippet of the output (I had to cut out some information): 

```

xxx languages of Latin script:
------------------------------
(...), Saafi-Saafi, Samburu, Samoan, Sango, Sangu (Tanzania), Saramaccan, Sardinian, Scots, Scottish Gaelic, Sena, Seri, Seselwa Creole French, Shambala, Shawnee, Shilluk, Shipibo-Conibo, Shona, Shuar, Sicilian, Silesian, Slovak, Slovenian, Soga, Somali, Soninke, South Azerbaijani, South Marquesan, South Ndebele, Southern Aymara, Southern Bobo Madaré, Southern Dagaare, Southern Qiandong Miao, Southern Sami, Southern Sotho, Spanish, Sranan Tongo, Standard Estonian, Standard Latvian, Standard Malay, Sundanese, Susu, Swahili, Swati, Swedish, Swiss German, Syenara Senoufo, (...)

xxx languages supported in total.

===============
Language check:
===============

Listing full support information for Serbian

autonym: Srpski
supported base characters: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ć Č Đ Ś Š Ź Ž a b c d e f g h i j k l m n o p q r s t u v w x y z ć č đ ś š ź ž
supported base marks: ́ ̌
supported auxiliary characters: Ǆ ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ
supported auxiliary marks: ́ ̌
missing base characters: 
missing base marks: 
missing auxiliary characters: 
missing auxiliary marks: 
script: Latin
status: primary
note: 

```

It seems that nothing is missing but the language is not included in the languages of Latin script/languages supported in total.

**Comment by MrBrezina** [comment]
Hi Marianna, can you try and inspect the font with the new [hyperglot-report](https://github.com/rosettatype/hyperglot#finding-almost-supported-languages) command?

**Comment by MariannaPaszkowska** [comment]
Hi, sure! I run hyperglot-report `No reporter option specified, reporting all issues (--report-all 0).`, and here are parts of the report. 

Here are all the mentions of Serbian:
```
Language (srp) Serbian missing characters for 'base': г, е, П, В, А, Г, О, ф, З, л, ћ, в, Р, Ђ, Ч, д, У, И, Ш, с, о, Е, Б, н, ч, љ, х, С, б, ј, К, ж, Л, Џ, а, Ф, р, Д, Х, Љ, Т, Ј, з, М, ђ, к, џ, Ћ, Ж, Ц, ц, Н, у, п, Њ, т, м, и, ш, њ
Language (srp) Serbian missing mark attachment for 'base': З́, С́, з́, с́
Language (srp) Serbian missing characters for 'base': г, е, П, В, А, Г, О, ф, З, л, ћ, в, Р, Ђ, Ч, д, У, И, Ш, с, о, Е, Б, н, ч, љ, х, С, б, ј, К, ж, Л, Џ, а, Ф, р, Д, Х, Љ, Т, Ј, з, М, ђ, к, џ, Ћ, Ж, Ц, ц, Н, у, п, Њ, т, м, и, ш, њ
Language (srp) Serbian missing mark attachment for 'base': З́, С́, з́, с́
```
Further down in the report:
```
Font has base support for:
===============================================

XXX languages of Latin script:
"(...)Saafi-Saafi, Samburu, Samoan, Sango, Sangu (Tanzania), Saramaccan, Sardinian, Saxwe Gbe, Scots, Scottish Gaelic, Secoya, Sena, Serer, Seri, Seselwa Creole French, Shambala, Sharanahua, Shawnee, Shilluk, Shipibo-Conibo, Shona, Shuar, Sicilian, Silesian, Siona, Slovak, Slovenian, Soga, Somali, Soninke, South Azerbaijani, South Marquesan, South Ndebele, Southern Aymara, Southern Bobo Madaré, Southern Dagaare, Southern Qiandong Miao, Southern Sami, Southern Sotho, Spanish, Sranan Tongo, Standard Estonian, Standard Latvian, Standard Malay, Sukuma, Sundanese, Susu, Swahili, Swati, Swedish, Swiss German, Syenara Senoufo, (...)"

**Comment by kontur** [comment]
The `preferred_as_group` [in the data](https://github.com/rosettatype/hyperglot/blob/b0e51439bdc67a6327b10f88bf873ad858907919/lib/hyperglot/data/srp.yaml#L10C3-L10C21) indicates that for Serbian all orthographies with that attribute are treated _as if they were one._ Or in other words, for Serbian support, a font needs both the Latin and Cyrillic, the reason being that both are deemed in use, e.g. from [Wikipedia](https://en.wikipedia.org/wiki/Serbian_language#Writing_system)

> Standard Serbian language uses both [Cyrillic](https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet) (ћирилица, ćirilica) and [Latin script](https://en.wikipedia.org/wiki/Gaj%27s_Latin_alphabet) (latinica, латиница). Serbian is a rare example of synchronic [digraphia](https://en.wikipedia.org/wiki/Digraphia), a situation where all literate members of a society have two interchangeable writing systems available to them. Media and publishers typically select one alphabet or the other. In general, the alphabets are used interchangeably; except in the legal sphere, where Cyrillic is required, there is no context where one alphabet or another predominates.

For a font to have support for Serbian it needs to support both, so the output from `hyperglot-report` tells you what specifically is missing.
