### ISSUE TITLE
Undefined status for many living languages

### ISSUE THREAD

**Issue by justinpenner** [rosettatype/hyperglot#167]
Can we add `status: living` to all languages that have a substantial number of speakers? I think it's fairly safe to assume that a language is living if it has more than zero speakers, but if there are any arguments against that assumption, a higher threshold would work.

The screenshot below illustrates some examples of languages with millions of speakers but are missing `status: living` in their YAML file.

<img width="532" alt="image" src="https://github.com/rosettatype/hyperglot/assets/46039243/12550412-bc5c-4997-a3c0-afc25ed35bc0">

**Comment by kontur** [comment]
Ah, you are correct! The [README](https://github.com/rosettatype/hyperglot/blob/8fdd804a622a46b222cf12294a5ee381e389eb5a/README_database.md?plain=1#L17) actually defines `living` as the default but the library does not return this value for when unset in the data. I'll fix that shortly!

**Comment by kontur** [comment]
Version `0.6.3` should fix this and the status values for languages should be "living" unless otherwise defined in the respective data yaml.
