### ISSUE TITLE
Requirements for the Hiragana and Katakana fonts are far too strict

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#168]
From Andreas Seidel:

Your requirements for the Hiragana and Katakana fonts are far too strict.

Please check this yourself on the pages of highly qualified Japanese
font manufacturers such as https://fontplus.jp/. Most Japanese fonts do
not have these characters.

These characters are not needed except for academic use.

characters don't needed for common Katakana:

U+30FF
U+31F0
U+31F1
U+31F2
U+31F3
U+31F4
U+31F5
U+31F6
U+31F7 + 309A
U+31F8
U+31FA
U+31FB
U+31FC
U+31FD
U+31FE
U+31FF

characters don't needed for common Hiragana:

U+309F

BTW: Large font like SourceHanSans or NotoSansJP freeze Hyperglot (website).

**Comment by kontur** [comment]
@sergiolmartins do you have any input on this? I'm inclined to follow the user reported suggestion; maybe the two digraphs (U+30FF for Katakana and U+309F for Hiragana) could be included in `auxiliary`, but the small version Katakana seem "orthographically" not needed.

**Comment by arrowtype** [comment]
Thank
