### ISSUE TITLE
Include a list of contributors for each language

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#178]
@kontur please, when we are done with the punctuation, add these yourself based on the Git data if you can and I will add manually those that I have represented and thus are not in the commit history

**Comment by kontur** [comment]
Roger that. I'll preemptively exclude myself and you from such detected changes, since we are likely to have touched any number of files with code formatting or other additions. We can manually add ourselves where relevant then after.

**Comment by kontur** [comment]
This was a bit more complex than anticipated, but I think I have nearly all. Specifically, I:
- for some languages went back to previous single file `hyperglot.yaml` and even earlier `rosetta.yaml` versions of the DB
- excluded bulk formatting by myself and @MrBrezina 
- added contributors from merges that appear in the git history
- added contributors mentioned in the CONTRIBUTORS.txt
- gone through git issues to find a few stray additions that were instructive only

All language files have `contributors` now. `hyperglot-validate` complains about files missing contributors. Here on out all language file changes should result in the author being mentioned with their name (or fallback to github user name if no name can be deferred, one such case). 🙏
