### ISSUE TITLE
Right single quotation mark (’)

### ISSUE THREAD

**Issue by meehkal** [rosettatype/hyperglot#36]
This comment regards Kildin Sami (sjd) specifically, but may also be relevant for other languages. 

This letter occurs only in printed texts from the 1990s and has never been defined digitally by the creators of the orthography. Digitally, it could also be a Modifier letter apostrophe (U+02BC) or Modifier letter prime (U+02B9), for instance.

**Comment by kontur** [comment]
Probably related to #43 and #45. So this should be listed in addition to the combining acute, right?

**Comment by kontur** [comment]
Resolved this now (for other Sami languages as well, consistently). Never mind my mention of combining acute ;)

Modifier letter apostrophe seems the most appropriate. Thank you for raising this issue.
