### ISSUE TITLE
Compare SIL SLDR database

### ISSUE THREAD

**Issue by kontur** [rosettatype/hyperglot#51]
https://github.com/silnrsi/sldr/tree/master/sldr

**Comment by twardoch** [comment]
I think SLDR may be a better primary source than CLDR, and also the info could flow back. SLDR’s motivation is much closer to Hyperglot than CLDR’s.

**Comment by kontur** [comment]
Akin to #52 (https://github.com/rosettatype/hyperglot/issues/52#issuecomment-853704844), I've added a comparison html in [tools/sldr_comparison.html](https://raw.githubusercontent.com/rosettatype/hyperglot/comparison/tools/sldr_comparison.html).

Compared to the CLDR there definitely is more "interesting" info for Hyperglot in terms of languages it does not yet cover.
