### ISSUE TITLE
Skolt Sami also requires Soft Sign (MODIFIER LETTER PRIME)

### ISSUE THREAD

**Issue by simoncozens** [rosettatype/hyperglot#63]
Sources:
* https://en.wikipedia.org/wiki/Skolt_Sami#Writing_system
* https://twitter.com/arjajomppanen/status/1442846076881489923

**Comment by MrBrezina** [comment]
Thanks @simoncozens !

@meehkal we should add these right?

**Comment by MrBrezina** [comment]
@meehkal I mean, should we add these to other Sami languages?

**Comment by meehkal** [comment]
Among the Saami languages it is only Skolt Saami which has this letter. Wasn't it included already?

If Akkala Saami (sia) would establish a writing system, it should best be written like Skolt Saami. But almost no texts have ever been printed in some kind of standardized orthography for Akkala.

**Comment by moyogo** [comment]
Hyperglot only has U+02BC MODIFIER LETTER APOSTROPHE at the moment.

Several Saami language references or documents use U+02B9 MODIFIER LETTER PRIME, some odd ones may use U+02CA MODIFIER LETTER ACUTE ACCENT, older ones used U+00B4 ACUTE ACCENT or even U+0027 APOSTROPHE, for the vowel suprasegmantal palatalization. 

U+02B9 MODIFIER LETTER PRIME should definitely be added to the base set.

U+02C8 MODIFIER LETTER VERTICAL LINE belongs in the auxiliary set as it appears in dictionaries.

**Comment by meehkal** [comment]
I've been involved in official discussions with the Skolt Saami community earlier. U+02B9 MODIFIER LETTER PRIME is the official character now, regardless was some other sources say.

**Comment by meehkal** [comment]
I've been involved in official discussions with the Skolt Saami community earlier. U+02B9 MODIFIER LETTER PRIME is the official character now, regardless was some other sources say.
