### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by m4rc1e** [rosettatype/hyperglot#70]
Hey @MrBrezina, long time no chat. Hope things are going well.

At GF, we've incorporated this tool and have included further regional data. However, we are seeing a lot more potential for this tool.

Some folks have been working on our character sets and they came up with the following ideas, https://gist.github.com/m4rc1e/f557a69d218056c4c5d0e373dc8c3071?permalink_comment_id=4027670#gistcomment-4027670

Sorry, this isn't an issue per se. Just some things we are thinking about at the moment.

**Comment by kontur** [comment]
Cheers for the head's up. Would be curious to compare what kinds of support output the tools generate. As mentioned in the gist comments I'd be happy to also take a look at what data you are using and how you are structuring it. The biggest difference to Hyperglot is probably that you work against fixed glyphsets per language, whereas Hyperglot distinguishes levels of support and different orthographies for each language — aside from possible differences in the data itself based on where they were sources from :)

**Comment by MrBrezina** [comment]
@m4rc1e hey, man! Hoe you are doing well, there. Thanks for the heads up. I will have a peek next week. There was a reason we avoided dealing with regions. I need to document our process better.

**Comment by kontur** [comment]
hey @m4rc1e I took quick look at how gftools (the gist aside) is using Hyperglot in the code and found how you're employing the parsing and subset check. If there's anything more specific you'd be interested in seeing implemented in Hyperglot we'd love to hear it of course. The actual comparison logic we have in the included CLI is naturally quite coupled to our data, e.g. the different support levels, language statuses, marks/decomposition flags etc., so not sure how we could make this more generally usable.

Also did a bit of digging to find the origin of the language data in the google/font "original" repo and seems language data just [appears](https://github.com/google/fonts/commit/13c45fe94cd268bc58c36acda1bdb70e6c0bb18f). Would be nice to know where it's coming from to do any kind of valuable comparison :)

**Comment by kontur** [comment]
Closing this as non-actionable. Glad to hear about the use and happy to discuss specifics on a per-issue basis if needed.
