### ISSUE TITLE
Wrong required letter in Turkish/Türkçe

### ISSUE THREAD

**Issue by obiobik** [rosettatype/hyperglot#71]
Instead of S-cedilla (U+15E) and s-cedilla (U+015F), S-comma(U+0218) and s-comma(U+0219) are listed as required letters. It has to be S-cedilla and s-cedilla.

Resources:
https://en.wikipedia.org/wiki/Ş
https://en.wikipedia.org/wiki/S-comma

**Comment by alerque** [comment]
Yes, this is correct. It also seems this mistake was made in several Turkic and related languages. I just submitted a PR to correct this in the data file, but I am not sure that is correct because the file may be generated based on some other data set.

**Comment by obiobik** [comment]
Probably. This mistake is also present in this similar project: https://underware.nl/latin_plus/

**Comment by alerque** [comment]
I sent an email to Underware noting the issue in their character set data.
