### ISSUE TITLE
Buginese Latin orthography uses Cyrillic Schwa/schwa. It should probably use the corresponding Latin codepoints.

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#77]
From @SorkinType:

> For the language Bugis/Buginese it looks like you have Cyrillic capital letter Schwa `U+04D8` and Cyrillic small letter schwa `U+04D9` listed as letters used by them (when using Latin script). I was expecting Schwa `U+018F` and schwa `U+0259`.

The use of a Cyrillic letter seems odd since the rest of the letters are Latin ones. No?

I tried this evening to find some references online that might support or disprove this information but I am coming up with nothing. Do you have any light to shed on this mystery? Any references?

<img width="667" alt="image" src="https://user-images.githubusercontent.com/485475/162701404-54d3e5f5-fe3b-437e-b2ee-69b4e237dcf3.png">

**Comment by MrBrezina** [comment]
@kontur fixed imho

**Comment by kontur** [comment]
Looking at commit [62721ea](https://github.com/rosettatype/hyperglot/commit/62721eaca98ca48579b774d0058cc4c6f8c07081) I am not sure it is. Now `bug` seems to link to `zsm` which doesn't have Schwa altogether. The original issue seems valid.

**Comment by kontur** [comment]
Also first time I learn of Schwa having a Latin and a Cyrillic code point. Could write a test for that (and possibly other similar ambivalent glyph encodings).

**Comment by kontur** [comment]
Roger that, didn't dig that deep. Let's keep this issue open until updated to pip 👍
