### ISSUE TITLE
Filter / sort option by number of speakers ?

### ISSUE THREAD

**Issue by RosaWagner** [rosettatype/hyperglot#78]
- could either be to sort languages by decreasing/increasing number of speakers
- or an option to only display languages over/below a certain number of users

**Comment by kontur** [comment]
Sounds useful. I'll probably have time to add this in end of May.

**Comment by kontur** [comment]
Having to delay this to June.

**Comment by kontur** [comment]
Btw, if you feel you can think of other useful sorting attributes, feel free to add [here](https://github.com/rosettatype/hyperglot/blob/f06c20e72c840dff442d91082ca3094c690a8a05/lib/hyperglot/__init__.py#L52), the item value is the sorting lambda that gets applied to each `Language` object.
