### ISSUE TITLE
English should have Àà (and not Áá?)

### ISSUE THREAD

**Issue by enbo** [rosettatype/hyperglot#89]
The English set is missing `Àà`, which is used in [French or pseudo-French expressions](https://en.wikipedia.org/wiki/Glossary_of_French_words_and_expressions_in_English#A).

I suspect that `Áá` should not be in the set. According to what I've found on Wikipedia, it's only used in very specific foreign terms: halászlé (Hungarian), páramo (Spanish), háček (Czech).

(For context I am a native American English speaker.)

Further reading:
* [English terms with diacritical marks (Wikipedia)](https://en.wikipedia.org/wiki/English_terms_with_diacritical_marks)
* [Font Language Support, English language (Typotheque)](https://www.typotheque.com/fonts/languages/english_language), which has `Àà` but not `Áá`.

**Comment by kontur** [comment]
Makes sense imo. The combining mark itself is present `´` and I imagine the `á` and cap version of it is one of the most prominent, auxiliary, uses.
