### ISSUE TITLE
Add Odia/Oriya support

### ISSUE THREAD

**Issue by MariannaPaszkowska** [rosettatype/hyperglot#95]
Would it be possible to add support for the Odia script?

**Comment by MrBrezina** [comment]
@MariannaPaszkowska thanks to super quick contribution by @moyogo we have the data now! It now waits for @kontur

**Comment by kontur** [comment]
✅  we'll get this merged in the end of September.

**Comment by kontur** [comment]
Took longer than that, but it is included now :)

**Comment by MariannaPaszkowska** [comment]
Fantastic, thank you! 

I noticed a small typo in the script's name (headline only, not the label).
It writes 'Orya' instead of 'Oriya': 
<img width="510" alt="Screenshot 2022-11-28 at 11 19 29 AM" src="https://user-images.githubusercontent.com/22956348/204240133-d0a94553-0088-474d-a4d0-2821b0d25586.png">

**Comment by kontur** [comment]
Ah, typo or maybe confusion stemming from e.g. the [iso 15924 code](https://en.wikipedia.org/wiki/ISO_15924#List_of_codes) — I'll fix this in the dev branch and it'll update with the next release.

**Comment by MariannaPaszkowska** [comment]
Thank you!

**Comment by kontur** [comment]
Fixed now in the library and on https://hyperglot.rosettatype.com/language/ori
